#!/usr/bin/bash

# this script will install all the makemake templates in this repo
# it assumes that you already have makemake installed in path
# you must have the NEW MAKEMAKE

type makemake &>/dev/null
EC=$?
if [[ $EC != 0 ]] ; then
    echo "Failure: makemake is not installed"
    exit 1
fi

PRMPT=${1:-no}

case "$PRMPT" in
    -h)
        echo "Welcome in the install-all script for makemake templates

Usage:
  install-all -h
    shows this help

  install-all [yes | no | ask]
    sets the default beahvior in case that any of the templates are already
    installed. The default value is 'no'."
        exit 0
        ;;
    yes|no|ask) ;;
    *)
        echo "Failure: invalid option $PRMPT"
        exit 1
        ;;
esac

if [ ${2:+x} ] ; then
    echo "Failure: too many arguments"
    exit 1
fi

makemake -p $PRMPT -cf mmt makemake/mmt
makemake -p $PRMPT -cf vscm C/vscm
makemake -p $PRMPT -cf lvscm C/lvscm
makemake -p $PRMPT -cf vscm++ C++/vscm++
makemake -p $PRMPT -cf lvscm++ C++/lvscm++
makemake -p $PRMPT -cf vasm asm/vasm
